USE [master]
GO

/****** Object:  Database [BillingSystem]    Script Date: 11/9/2025 11:16:45 ******/
CREATE DATABASE [BillingSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BillingSystem', FILENAME = N'C:\Users\marti\BillingSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BillingSystem_log', FILENAME = N'C:\Users\marti\BillingSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BillingSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BillingSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BillingSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BillingSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BillingSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BillingSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [BillingSystem] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BillingSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BillingSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BillingSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BillingSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BillingSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BillingSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BillingSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BillingSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BillingSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BillingSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BillingSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BillingSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BillingSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BillingSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BillingSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BillingSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BillingSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BillingSystem] SET  MULTI_USER 
GO

ALTER DATABASE [BillingSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BillingSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BillingSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BillingSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BillingSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BillingSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BillingSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BillingSystem] SET  READ_WRITE 
GO

